# Default values for cube.

namespace: cube

cube:
  cubeDockerSecret: SOMESTRONGSECRET
  cubewsImageTag: 70c2a51f534820c6fab977f3e6c31d21aa77e94c-master
  cubeuiImageTag: f4becadd69326b61aaf38decf599d3304f47d766-master
  cubeuibackendImageTag: bb9a0a70d7056c499a8ed52541185ef6303322c0-master
  uibackendReplica: 1
  replayReplica: 1
  recordReplica: 1
  mockReplica: 1
  uiReplica: 1
  host: "*"
  solrCore: cube
  solrURL: http://SOLR_URL:8983/solr/
  springbootProfile: azure
  springbootURL: jdbc:postgresql://SOME_URL:5432/DATABASE_NAME?schema=qui
  springbootUsername: DATABASE_USERNAME
  springbootpassword: PASSWORD_FOR_DB_USER

redis:
  replica: 1