---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cube
  namespace: {{ .Values.namespace }}
spec:
  gateways:
  - {{ .Values.namespace }}-gateway
  hosts:
  - "{{ .Values.cube.host }}"
  http:
  - match:
    - uri:
        prefix: /api/
    route:
    - destination:
        host: cubeui-backend
        port:
          number: 8080
  - match:
    - uri:
        exact: /
    - uri:
        prefix: /assets
    - uri:
        regex: ^.*\.(ico|png|jpg|js|css)$
    - uri:
        prefix: /
    route:
    - destination:
        host: cubeui
        port:
          number: 80

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cube-pvt
  namespace: {{ .Values.namespace }}
spec:
  gateways:
  - {{ .Values.namespace }}-pvt-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /cs/
    route:
    - destination:
        host: cubews-record
        port:
          number: 8080
  - match:
    - uri:
        prefix: /ms/
    route:
    - destination:
        host: cubews-mock
        port:
          number: 8080
  - match:
    - uri:
        prefix: /rs/
    - uri:
        prefix: /as/
    route:
    - destination:
        host: cubews-replay
        port:
          number: 8080